name: Release Components

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-exclude-test-apps-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-exclude-test-apps-
      - uses: pnpm/action-setup@v2.2.4
        with:
          run_install: |
            - args: [--filter=\!./frameworks/\*/tests/apps/\*]
      - name: Update NPM token
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - id: checkApiVersion
        uses: PostHog/check-package-version@v2
        with:
          path: ./api
      - id: checkAppVersion
        uses: PostHog/check-package-version@v2
        with:
          path: ./app
      - id: checkChromelessVersion
        uses: PostHog/check-package-version@v2
        with:
          path: ./chromeless
      - id: checkConfigVersion
        uses: PostHog/check-package-version@v2
        with:
          path: ./config
      - id: checkConfigHelperNextjsVersion
        uses: PostHog/check-package-version@v2
        with:
          path: ./config-helpers/nextjs
      - id: checkCoreVersion
        uses: PostHog/check-package-version@v2
        with:
          path: ./core
      - id: checkCsf3Version
        uses: PostHog/check-package-version@v2
        with:
          path: ./csf3
      - id: checkIframeVersion
        uses: PostHog/check-package-version@v2
        with:
          path: ./iframe
      - id: checkPluginPreactVersion
        uses: PostHog/check-package-version@v2
        with:
          path: ./frameworks/preact
      - id: checkPluginReactVersion
        uses: PostHog/check-package-version@v2
        with:
          path: ./frameworks/react
      - id: checkPluginSolidVersion
        uses: PostHog/check-package-version@v2
        with:
          path: ./frameworks/solid
      - id: checkPluginSvelteVersion
        uses: PostHog/check-package-version@v2
        with:
          path: ./frameworks/svelte
      - id: checkPluginVue2Version
        uses: PostHog/check-package-version@v2
        with:
          path: ./frameworks/vue2
      - id: checkPluginVue3Version
        uses: PostHog/check-package-version@v2
        with:
          path: ./frameworks/vue3
      - id: checkPropertiesVersion
        uses: PostHog/check-package-version@v2
        with:
          path: ./properties
      - id: checkSerializableValuesVersion
        uses: PostHog/check-package-version@v2
        with:
          path: ./serializable-values
      - id: checkTestingVersion
        uses: PostHog/check-package-version@v2
        with:
          path: ./testing
      - id: checkTypeAnalyzerVersion
        uses: PostHog/check-package-version@v2
        with:
          path: ./type-analyzer
      - id: checkVfsVersion
        uses: PostHog/check-package-version@v2
        with:
          path: ./vfs
      - if: steps.checkApiVersion.outputs.is-new-version
        run: cd api && pnpm publish --no-git-checks --access public
      - if: steps.checkAppVersion.outputs.is-new-version
        run: cd app && pnpm publish --no-git-checks --access public
      - if: steps.checkChromelessVersion.outputs.is-new-version
        run: cd chromeless && pnpm publish --no-git-checks --access public
      - if: steps.checkConfigVersion.outputs.is-new-version
        run: cd config && pnpm publish --no-git-checks --access public
      - if: steps.checkConfigHelperNextjsVersion.outputs.is-new-version
        run: cd config-helpers/nextjs && pnpm publish --no-git-checks --access public
      - if: steps.checkCoreVersion.outputs.is-new-version
        run: cd core && pnpm publish --no-git-checks --access public
      - if: steps.checkCsf3Version.outputs.is-new-version
        run: cd csf3 && pnpm publish --no-git-checks --access public
      - if: steps.checkIframeVersion.outputs.is-new-version
        run: cd iframe && pnpm publish --no-git-checks --access public
      - if: steps.checkPluginPreactVersion.outputs.is-new-version
        run: cd frameworks/preact && pnpm publish --no-git-checks --access public
      - if: steps.checkPluginReactVersion.outputs.is-new-version
        run: cd frameworks/react && pnpm publish --no-git-checks --access public
      - if: steps.checkPluginSolidVersion.outputs.is-new-version
        run: cd frameworks/solid && pnpm publish --no-git-checks --access public
      - if: steps.checkPluginSvelteVersion.outputs.is-new-version
        run: cd frameworks/svelte && pnpm publish --no-git-checks --access public
      - if: steps.checkPluginVue2Version.outputs.is-new-version
        run: cd frameworks/vue2 && pnpm publish --no-git-checks --access public
      - if: steps.checkPluginVue3Version.outputs.is-new-version
        run: cd frameworks/vue3 && pnpm publish --no-git-checks --access public
      - if: steps.checkPropertiesVersion.outputs.is-new-version
        run: cd properties && pnpm publish --no-git-checks --access public
      - if: steps.checkSerializableValuesVersion.outputs.is-new-version
        run: cd serializable-values && pnpm publish --no-git-checks --access public
      - if: steps.checkTestingVersion.outputs.is-new-version
        run: cd testing && pnpm publish --no-git-checks --access public
      - if: steps.checkTypeAnalyzerVersion.outputs.is-new-version
        run: cd type-analyzer && pnpm publish --no-git-checks --access public
      - if: steps.checkVfsVersion.outputs.is-new-version
        run: cd vfs && pnpm publish --no-git-checks --access public
